const JSON_HEADERS={"content-type":"application/json; charset=utf-8"};

function cors(origin,allowed){
  return {...JSON_HEADERS,"access-control-allow-origin":origin===allowed?origin:allowed,"access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,x-idempotency-key,authorization","access-control-max-age":"86400","vary":"Origin"};
}

function reply(body,status,origin,allowed){
  return new Response(JSON.stringify(body),{status,headers:cors(origin,allowed)});
}

function clean(value,max=500){return String(value??'').trim().replace(/\s+/g,' ').slice(0,max)}

function validate(input){
  const allowedTypes=new Set(['person','surname','address','organization','expertise','free']);
  const lead={
    id:Number(input?.id)||Date.now(),type:clean(input?.type,32),type_label:clean(input?.type_label,80),
    value:clean(input?.value,180),location:clean(input?.location,180),note:clean(input?.note,1000),
    created_at:new Date().toISOString()
  };
  if(!allowedTypes.has(lead.type))throw new Error('نوع سرنخ معتبر نیست.');
  if(lead.value.length<2)throw new Error('مقدار سرنخ باید حداقل دو نویسه باشد.');
  return lead;
}

function issueBody(lead){
  return `سرنخ انسانی ثبت‌شده برای خط لولهٔ کشف SCIE.\n\n<!--SCIE_LEAD\n${JSON.stringify(lead,null,2)}\nSCIE_LEAD-->\n\n- نوع: ${lead.type_label||lead.type}\n- مقدار: ${lead.value}\n- مکان: ${lead.location||'ثبت نشده'}\n- انتظار: جستجو، اعتبارسنجی و افزودن نامزدهای جدید به Snapshot داشبورد`;
}

function validateFeedback(input){
  const kind=clean(input?.kind,32),base={id:Number(input?.id)||Date.now(),kind,created_at:new Date().toISOString()};
  if(kind==='locality_review'){
    const verdict=clean(input?.verdict,32);if(!['ardakani','not_ardakani','needs_evidence'].includes(verdict))throw new Error('نتیجهٔ راستی‌آزمایی معتبر نیست.');
    return {...base,record_index:Number(input?.record_index),person_name:clean(input?.person_name,180),verdict,reason:clean(input?.reason,120),note:clean(input?.note,1000)};
  }
  if(kind==='relationship'){
    const value={...base,person_a:clean(input?.person_a,180),person_b:clean(input?.person_b,180),relation:clean(input?.relation,32),note:clean(input?.note,1000)};
    if(!value.person_a||!value.person_b||value.person_a===value.person_b)throw new Error('دو فرد متفاوت را انتخاب کنید.');return value;
  }
  if(kind==='source_review'){
    const verdict=clean(input?.verdict,40);if(!['person_candidate','relevant_nonperson','irrelevant','needs_evidence'].includes(verdict))throw new Error('نتیجهٔ بررسی منبع معتبر نیست.');
    const value={...base,source_url:clean(input?.source_url,600),platform:clean(input?.platform,40),verdict,note:clean(input?.note,1000)};
    if(!/^https?:\/\//.test(value.source_url))throw new Error('نشانی منبع معتبر نیست.');return value;
  }
  throw new Error('نوع بازخورد معتبر نیست.');
}

function feedbackIssue(item){
  const relation=item.kind==='relationship',source=item.kind==='source_review',title=relation?`[SCIE RELATIONSHIP] ${item.person_a} ↔ ${item.person_b}`:source?`[SCIE SOURCE REVIEW] ${item.platform}`:`[SCIE FEEDBACK] ${item.person_name}`;
  const body=`بازخورد انسانی برای پردازش SCIE.\n\n<!--SCIE_FEEDBACK\n${JSON.stringify(item,null,2)}\nSCIE_FEEDBACK-->\n\nاین ادعا تا زمان تأیید با شواهد مستقل، بازخورد انسانی محسوب می‌شود.`;
  return {title,body};
}

function base64Decode(value){return new TextDecoder().decode(Uint8Array.from(atob(value.replace(/\n/g,'')),char=>char.charCodeAt(0)))}
function base64Encode(value){const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
function secureEqual(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let mismatch=0;for(let i=0;i<a.length;i++)mismatch|=a.charCodeAt(i)^b.charCodeAt(i);return mismatch===0}
const base64Url=value=>base64Encode(value).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
async function tokenSignature(payload,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),signature=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload));return btoa(String.fromCharCode(...new Uint8Array(signature))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function issueAdminToken(username,secret){const payload=base64Url(JSON.stringify({u:username,v:1}));return `${payload}.${await tokenSignature(payload,secret)}`}
async function isAdmin(request,env){const token=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,''),[payload,signature]=token.split('.');if(!payload||!signature||!env.ADMIN_KEY)return false;return secureEqual(signature,await tokenSignature(payload,env.ADMIN_KEY))}
async function loginAdmin(request,env,origin,allowed){const input=await request.json(),username=clean(input?.username,80),password=String(input?.password||'');if(!secureEqual(username,env.ADMIN_USERNAME||'admin')||!secureEqual(password,env.ADMIN_KEY||''))return reply({ok:false,error:'نام کاربری یا رمز عبور نادرست است.'},401,origin,allowed);return reply({ok:true,token:await issueAdminToken(username,env.ADMIN_KEY),username},200,origin,allowed)}
async function updateRecord(request,env,origin,allowed){
  if(!await isAdmin(request,env))return reply({ok:false,error:'نشست مدیریت معتبر نیست یا دسترسی مجاز نیست.'},401,origin,allowed);
  const input=await request.json(),index=Number(input?.record_index),allowedFields=new Set(['name','name_fa','type','source','verification','organization_fa','affiliation','location','specialty','specialty_en','specialty_evidence','specialty_source_url','detail','url']),changes={};
  if(!Number.isInteger(index)||index<0)throw new Error('شماره رکورد معتبر نیست.');
  for(const [key,value] of Object.entries(input?.changes||{})){if(!allowedFields.has(key))throw new Error(`ویرایش فیلد ${key} مجاز نیست.`);changes[key]=clean(value,key==='detail'?2000:600)}
  if(!Object.keys(changes).length)throw new Error('هیچ تغییری برای ذخیره ارسال نشده است.');
  const endpoint=`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/contents/docs/data.json`,headers={authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'SCIE-Admin-API','x-github-api-version':'2022-11-28'};
  const currentResponse=await fetch(endpoint,{headers});const current=await currentResponse.json();if(!currentResponse.ok)throw new Error(`دریافت داده برای ویرایش ناموفق بود: ${current?.message||currentResponse.status}`);
  const document=JSON.parse(base64Decode(current.content)),records=Array.isArray(document)?document:(document.people||document.records||document.items);if(!Array.isArray(records)||!records[index])throw new Error('رکورد موردنظر پیدا نشد.');
  Object.assign(records[index],changes);document.generated_at=new Date().toISOString();
  const saveResponse=await fetch(endpoint,{method:'PUT',headers,body:JSON.stringify({message:`data: admin edit record ${index}`,content:base64Encode(JSON.stringify(document,null,2)+'\n'),sha:current.sha,branch:'main'})}),saved=await saveResponse.json();
  if(!saveResponse.ok)throw new Error(`ذخیره ویرایش ناموفق بود: ${saved?.message||saveResponse.status}`);
  return reply({ok:true,status:'saved',record_index:index,changes,commit:saved.commit?.sha||''},200,origin,allowed);
}
async function updateRelationship(request,env,origin,allowed){
  if(!await isAdmin(request,env))return reply({ok:false,error:'نشست مدیریت معتبر نیست یا دسترسی مجاز نیست.'},401,origin,allowed);
  const input=await request.json(),endpoint=`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/contents/docs/relationships.json`,headers={authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'SCIE-Admin-API','x-github-api-version':'2022-11-28'};
  const currentResponse=await fetch(endpoint,{headers});const current=await currentResponse.json();if(!currentResponse.ok)throw new Error(`دریافت ارتباطات ناموفق بود: ${current?.message||currentResponse.status}`);const document=JSON.parse(base64Decode(current.content));document.relationships=Array.isArray(document.relationships)?document.relationships:[];
  let relationship=null;if(input.action==='delete'){document.relationships=document.relationships.filter(item=>String(item.id)!==String(input.id))}else{const a=Number(input.person_a_index),b=Number(input.person_b_index),allowedTypes=new Set(['family','colleague','organization','expertise','education','social','other']);if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0||a===b)throw new Error('دو فرد معتبر و متفاوت انتخاب کنید.');const type=clean(input.type,32);if(!allowedTypes.has(type))throw new Error('نوع ارتباط معتبر نیست.');relationship={id:crypto.randomUUID(),person_a_index:a,person_b_index:b,type,note:clean(input.note,500),updated_at:new Date().toISOString()};document.relationships.push(relationship)}document.generated_at=new Date().toISOString();
  const saveResponse=await fetch(endpoint,{method:'PUT',headers,body:JSON.stringify({message:`data: admin ${input.action==='delete'?'delete':'add'} relationship`,content:base64Encode(JSON.stringify(document,null,2)+'\n'),sha:current.sha,branch:'main'})}),saved=await saveResponse.json();if(!saveResponse.ok)throw new Error(`ذخیره ارتباط ناموفق بود: ${saved?.message||saveResponse.status}`);return reply({ok:true,status:'saved',relationship,commit:saved.commit?.sha||''},200,origin,allowed)
}

const fromBase64Url=value=>base64Decode(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4));
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:120000},key,256);return [...new Uint8Array(bits)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function issueToken(user,secret){const payload=base64Url(JSON.stringify({id:user.id,u:user.username,role:user.role||'user',v:2}));return `${payload}.${await tokenSignature(payload,secret)}`}
async function currentUser(request,env){const token=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,''),[payload,signature]=token.split('.');if(!payload||!signature||!env.ADMIN_KEY||!secureEqual(signature,await tokenSignature(payload,env.ADMIN_KEY)))return null;try{const claims=JSON.parse(fromBase64Url(payload));if(claims.role==='admin'&&claims.u===(env.ADMIN_USERNAME||'admin'))return {id:'admin',username:claims.u,role:'admin'};return await env.DB.prepare('SELECT id, username, role, created_at FROM users WHERE id = ?').bind(claims.id).first()}catch{return null}}
async function authRoute(request,env,origin,allowed,mode){const input=await request.json(),username=clean(input?.username,50),password=String(input?.password||'');if(!/^[A-Za-z0-9_.-]{3,50}$/.test(username)||password.length<8)return reply({ok:false,error:'نام کاربری باید حداقل ۳ نویسه و رمز عبور حداقل ۸ نویسه باشد.'},400,origin,allowed);if(mode==='login'&&secureEqual(username,env.ADMIN_USERNAME||'admin')&&secureEqual(password,env.ADMIN_KEY||'')){const user={id:'admin',username,role:'admin'};return reply({ok:true,token:await issueToken(user,env.ADMIN_KEY),user},200,origin,allowed)}if(mode==='register'){const exists=await env.DB.prepare('SELECT id FROM users WHERE username = ?').bind(username).first();if(exists)return reply({ok:false,error:'این نام کاربری قبلاً ثبت شده است.'},409,origin,allowed);const id=crypto.randomUUID(),salt=crypto.randomUUID(),hash=await passwordHash(password,salt),created=new Date().toISOString();await env.DB.prepare('INSERT INTO users (id,username,password_hash,salt,role,created_at) VALUES (?,?,?,?,?,?)').bind(id,username,hash,salt,'user',created).run();const user={id,username,role:'user',created_at:created};return reply({ok:true,token:await issueToken(user,env.ADMIN_KEY),user},201,origin,allowed)}const record=await env.DB.prepare('SELECT * FROM users WHERE username = ?').bind(username).first();if(!record||!secureEqual(record.password_hash,await passwordHash(password,record.salt)))return reply({ok:false,error:'نام کاربری یا رمز عبور نادرست است.'},401,origin,allowed);const user={id:record.id,username:record.username,role:record.role,created_at:record.created_at};return reply({ok:true,token:await issueToken(user,env.ADMIN_KEY),user},200,origin,allowed)}
async function d1UpdateRecord(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'این عملیات فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),index=Number(input?.record_index),allowedFields=new Set(['name','name_fa','type','source','verification','organization_fa','affiliation','location','specialty','specialty_en','specialty_evidence','specialty_source_url','detail','url']),changes={};if(!Number.isInteger(index)||index<0)throw new Error('شماره رکورد معتبر نیست.');for(const [field,value] of Object.entries(input?.changes||{})){if(!allowedFields.has(field))throw new Error('فیلد ویرایش مجاز نیست.');changes[field]=clean(value,field==='detail'||field==='specialty_evidence'?2000:600)}const now=new Date().toISOString(),statements=[];for(const [field,value] of Object.entries(changes)){const current=await env.DB.prepare('SELECT value FROM record_overrides WHERE record_index=? AND field=?').bind(index,field).first(),versionId=crypto.randomUUID();statements.push(env.DB.prepare("INSERT INTO record_versions(id,record_index,field,previous_value,new_value,action,changed_by,changed_at) VALUES(?,?,?,?,?,'edit',?,?)").bind(versionId,index,field,current?.value??null,value,user.id,now));statements.push(env.DB.prepare('INSERT INTO record_overrides(record_index,field,value,updated_by,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(record_index,field) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(index,field,value,user.id,now))}if(statements.length)await env.DB.batch(statements);await logActivity(env,user,'record_edit',`ویرایش رکورد ${index}`,{changes});return reply({ok:true,status:'saved',record_index:index,changes},200,origin,allowed)}
async function importRecords(request,env,origin,allowed){
  const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'ورود گروهی فقط برای مدیر سامانه مجاز است.'},403,origin,allowed);
  const input=await request.json(),incoming=Array.isArray(input?.records)?input.records.slice(0,1000):[];if(!incoming.length)throw new Error('فایل هیچ رکورد معتبری ندارد.');if(!env.GITHUB_TOKEN)return reply({ok:false,error:'سرویس ذخیره‌سازی پیکربندی نشده است.'},503,origin,allowed);
  const allowedFields=new Set(['name','name_fa','type','source','verification','confidence','specialty','specialty_en','specialty_evidence','specialty_source_url','affiliation','organization_fa','location','detail','url','evidence']),endpoint=`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/contents/docs/data.json`,headers={authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'SCIE-Bulk-Import','x-github-api-version':'2022-11-28'};
  const currentResponse=await fetch(endpoint,{headers}),current=await currentResponse.json();if(!currentResponse.ok)throw new Error(`دریافت مخزن داده ناموفق بود: ${current?.message||currentResponse.status}`);const document=JSON.parse(base64Decode(current.content)),people=document.people||[],key=value=>clean(value,700).toLocaleLowerCase('fa'),byUrl=new Map(),byName=new Map();people.forEach((person,index)=>{if(person.url)byUrl.set(key(person.url),index);const name=key(person.name_fa||person.name);if(name)byName.set(name,index)});
  let added=0,updated=0;const addedRecords=[];for(const raw of incoming){const record={};for(const [field,value] of Object.entries(raw||{})){if(!allowedFields.has(field))continue;if(field==='evidence')record.evidence=(Array.isArray(value)?value:String(value||'').split('|')).map(item=>clean(item,1000)).filter(Boolean);else record[field]=clean(value,field==='specialty_evidence'||field==='detail'?2000:700)}if(!record.name&&!record.name_fa)continue;if(!record.source&&!record.url)continue;record.source=record.source||'ورود گروهی تأییدشده';record.type=record.type||'رکورد قطعی واردشده';record.verification='confirmed_by_admin';record.confidence='high';record.imported_at=new Date().toISOString();const match=(record.url&&byUrl.get(key(record.url)))??byName.get(key(record.name_fa||record.name));if(match!==undefined){Object.assign(people[match],Object.fromEntries(Object.entries(record).filter(([,value])=>value!==''&&!(Array.isArray(value)&&!value.length))));updated++}else{people.push(record);const index=people.length-1;if(record.url)byUrl.set(key(record.url),index);byName.set(key(record.name_fa||record.name),index);addedRecords.push(record);added++}}
  document.generated_at=new Date().toISOString();document.stats=document.stats||{};document.stats.people=people.length;const save=await fetch(endpoint,{method:'PUT',headers,body:JSON.stringify({message:`data: import ${added} confirmed records`,content:base64Encode(JSON.stringify(document,null,2)+'\n'),sha:current.sha,branch:'main'})}),saved=await save.json();if(!save.ok)throw new Error(`ذخیره فایل ورودی ناموفق بود: ${saved?.message||save.status}`);await logActivity(env,user,'bulk_import',`ورود گروهی ${added} رکورد جدید و تکمیل ${updated} رکورد`,{added,updated});return reply({ok:true,added,updated,added_records:addedRecords,total:people.length},200,origin,allowed)
}
async function d1Relationship(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'این عملیات فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json();if(input.action==='delete'){await env.DB.prepare('DELETE FROM relationships WHERE id=?').bind(clean(input.id,80)).run();await logActivity(env,user,'relationship_delete','حذف یک ارتباط',{id:input.id});return reply({ok:true,status:'deleted'},200,origin,allowed)}const a=Number(input.person_a_index),b=Number(input.person_b_index),type=clean(input.type,32),allowedTypes=new Set(['family','colleague','organization','expertise','education','social','other']);if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0||a===b||!allowedTypes.has(type))throw new Error('اطلاعات ارتباط معتبر نیست.');const relationship={id:crypto.randomUUID(),person_a_index:a,person_b_index:b,type,note:clean(input.note,500),updated_by:user.id,updated_at:new Date().toISOString()};await env.DB.prepare('INSERT INTO relationships(id,person_a_index,person_b_index,type,note,updated_by,updated_at) VALUES(?,?,?,?,?,?,?)').bind(...Object.values(relationship)).run();await logActivity(env,user,'relationship_add','افزودن ارتباط بین افراد',relationship);return reply({ok:true,status:'saved',relationship},200,origin,allowed)}
function mergeInput(input){const primary=Number(input?.primary_index),duplicate=Number(input?.duplicate_index);if(!Number.isInteger(primary)||!Number.isInteger(duplicate)||primary<0||duplicate<0||primary===duplicate)throw new Error('دو رکورد معتبر و متفاوت را انتخاب کنید.');return {primary,duplicate,reason:clean(input?.reason,600),confidence:Math.max(0,Math.min(100,Number(input?.confidence)||0)),evidence:input?.evidence&&typeof input.evidence==='object'?input.evidence:{}}}
async function applyMerge(env,{primary,duplicate,requestId,user}){const existing=await env.DB.prepare('SELECT primary_index FROM record_merges WHERE duplicate_index=?').bind(duplicate).first();if(existing&&Number(existing.primary_index)!==primary)throw new Error('این رکورد قبلاً با رکورد دیگری ادغام شده است.');const now=new Date().toISOString();await env.DB.prepare('INSERT INTO record_merges(duplicate_index,primary_index,request_id,merged_by,merged_at) VALUES(?,?,?,?,?) ON CONFLICT(duplicate_index) DO UPDATE SET primary_index=excluded.primary_index,request_id=excluded.request_id,merged_by=excluded.merged_by,merged_at=excluded.merged_at').bind(duplicate,primary,requestId,user.id,now).run();return now}
async function proposeMerge(request,env,origin,allowed){const user=await currentUser(request,env);if(!user)return reply({ok:false,error:'برای پیشنهاد ادغام ابتدا وارد حساب شوید.'},401,origin,allowed);const input=await request.json(),data=mergeInput(input),reverse=await env.DB.prepare("SELECT id,status FROM merge_requests WHERE ((primary_index=? AND duplicate_index=?) OR (primary_index=? AND duplicate_index=?)) AND status='pending' LIMIT 1").bind(data.primary,data.duplicate,data.duplicate,data.primary).first();if(reverse)return reply({ok:true,status:'pending',request_id:reverse.id,duplicate:true},200,origin,allowed);const id=crypto.randomUUID(),now=new Date().toISOString(),status=user.role==='admin'?'applied':'pending';await env.DB.prepare('INSERT INTO merge_requests(id,primary_index,duplicate_index,reason,confidence,evidence_json,status,proposed_by,reviewed_by,created_at,reviewed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,data.primary,data.duplicate,data.reason,data.confidence,JSON.stringify(data.evidence),status,user.id,user.role==='admin'?user.id:null,now,user.role==='admin'?now:null).run();if(user.role==='admin')await applyMerge(env,{...data,requestId:id,user});await logActivity(env,user,user.role==='admin'?'merge_apply':'merge_proposal',user.role==='admin'?'ادغام مستقیم دو رکورد':'پیشنهاد ادغام دو رکورد',{id,...data,status});return reply({ok:true,status,request:{id,primary_index:data.primary,duplicate_index:data.duplicate,reason:data.reason,confidence:data.confidence,status,proposed_by:user.username,created_at:now}},user.role==='admin'?200:202,origin,allowed)}
async function reviewMerge(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'بررسی پیشنهاد ادغام فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),id=clean(input?.id,80),action=clean(input?.action,20);if(!['approve','reject'].includes(action))throw new Error('تصمیم بررسی معتبر نیست.');const item=await env.DB.prepare("SELECT * FROM merge_requests WHERE id=? AND status='pending'").bind(id).first();if(!item)throw new Error('پیشنهاد در انتظار بررسی پیدا نشد.');const now=new Date().toISOString(),status=action==='approve'?'approved':'rejected';if(action==='approve')await applyMerge(env,{primary:Number(item.primary_index),duplicate:Number(item.duplicate_index),requestId:id,user});await env.DB.prepare('UPDATE merge_requests SET status=?,reviewed_by=?,reviewed_at=? WHERE id=?').bind(status,user.id,now,id).run();await logActivity(env,user,action==='approve'?'merge_approve':'merge_reject',action==='approve'?'تأیید و اعمال ادغام رکوردها':'رد پیشنهاد ادغام',{id,primary_index:item.primary_index,duplicate_index:item.duplicate_index});return reply({ok:true,status,merge:action==='approve'?{primary_index:item.primary_index,duplicate_index:item.duplicate_index,request_id:id,merged_by:user.id,merged_at:now}:null},200,origin,allowed)}
async function listMerges(request,env,origin,allowed){const user=await currentUser(request,env);if(!user)return reply({ok:false,error:'ابتدا وارد حساب شوید.'},401,origin,allowed);const query=user.role==='admin'?'SELECT m.*,u.username AS proposed_by_name FROM merge_requests m LEFT JOIN users u ON u.id=m.proposed_by ORDER BY m.created_at DESC LIMIT 200':'SELECT m.*,u.username AS proposed_by_name FROM merge_requests m LEFT JOIN users u ON u.id=m.proposed_by WHERE m.proposed_by=? ORDER BY m.created_at DESC LIMIT 100',result=user.role==='admin'?await env.DB.prepare(query).all():await env.DB.prepare(query).bind(user.id).all();return reply({ok:true,requests:result.results||[]},200,origin,allowed)}
async function createReverification(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'بازبینی ویژه فقط برای مدیر سامانه مجاز است.'},403,origin,allowed);const input=await request.json(),index=Number(input?.record_index),name=clean(input?.person_name,180),reason=clean(input?.reason,1200);if(!Number.isInteger(index)||index<0||!name)throw new Error('رکورد انتخاب‌شده معتبر نیست.');const recent=await env.DB.prepare("SELECT * FROM reverification_requests WHERE record_index=? AND status IN ('queued','processing') ORDER BY created_at DESC LIMIT 1").bind(index).first();if(recent)return reply({ok:true,status:recent.status,request:recent,duplicate:true},200,origin,allowed);const id=crypto.randomUUID(),created=new Date().toISOString();await env.DB.prepare('INSERT INTO reverification_requests(id,record_index,person_name,reason,status,requested_by,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,index,name,reason,'queued',user.id,created).run();let issueNumber=null;if(env.GITHUB_TOKEN){const endpoint=`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/issues`,headers={authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'SCIE-Reverification','x-github-api-version':'2022-11-28'},body=`درخواست بازبینی ویژه مدیریتی برای یک رکورد اطلس.\n\n<!--SCIE_REVERIFY\n${JSON.stringify({id,record_index:index,person_name:name,reason,requested_at:created},null,2)}\nSCIE_REVERIFY-->\n\nانتظار: بازخوانی منشأ، جستجوی شاهد مستقل، ارزیابی ارتباط با اردکان، بررسی هویت و ثبت نتیجه مستند.`;const response=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify({title:`[SCIE REVERIFY] ${name}`,body})}),issue=await response.json();if(response.ok){issueNumber=issue.number;await env.DB.prepare('UPDATE reverification_requests SET issue_number=? WHERE id=?').bind(issueNumber,id).run()}}await logActivity(env,user,'reverification_request',`درخواست بازبینی ویژه ${name}`,{id,record_index:index,reason,issue_number:issueNumber});return reply({ok:true,status:'queued',request:{id,record_index:index,person_name:name,reason,status:'queued',issue_number:issueNumber,created_at:created}},201,origin,allowed)}
async function syncReverification(env,row){if(!row?.issue_number||!env.GITHUB_TOKEN||!['queued','processing'].includes(row.status))return row;const headers={authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','user-agent':'SCIE-Reverification','x-github-api-version':'2022-11-28'},base=`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/issues/${row.issue_number}`,response=await fetch(base,{headers});if(!response.ok)return row;const issue=await response.json();if(issue.state==='open'){if(row.status==='queued'){await env.DB.prepare("UPDATE reverification_requests SET status='processing' WHERE id=?").bind(row.id).run();row.status='processing'}return row}const commentsResponse=await fetch(`${base}/comments?per_page=100`,{headers}),comments=commentsResponse.ok?await commentsResponse.json():[],last=comments.at(-1),result={issue_url:issue.html_url,closed_at:issue.closed_at,state_reason:issue.state_reason,summary:clean(last?.body||'بازبینی پایان یافته و پرونده بسته شده است.',4000)},completed=issue.closed_at||new Date().toISOString();await env.DB.prepare("UPDATE reverification_requests SET status='completed',result_json=?,completed_at=? WHERE id=?").bind(JSON.stringify(result),completed,row.id).run();return {...row,status:'completed',result_json:JSON.stringify(result),completed_at:completed}}
async function listReverification(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'مشاهده بازبینی ویژه فقط برای مدیر مجاز است.'},403,origin,allowed);const index=Number(new URL(request.url).searchParams.get('record_index'));if(!Number.isInteger(index)||index<0)throw new Error('شماره رکورد معتبر نیست.');const rows=await env.DB.prepare('SELECT id,record_index,person_name,reason,status,issue_number,result_json,created_at,completed_at FROM reverification_requests WHERE record_index=? ORDER BY created_at DESC LIMIT 20').bind(index).all(),synced=[];for(const row of rows.results||[])synced.push(await syncReverification(env,row));return reply({ok:true,requests:synced},200,origin,allowed)}
async function logActivity(env,user,kind,summary,payload){if(!user)return;const now=new Date().toISOString();if(user.role==='admin')await env.DB.prepare("INSERT OR IGNORE INTO users(id,username,password_hash,salt,role,created_at) VALUES('admin',?,'managed-by-worker','managed-by-worker','admin',?)").bind(user.username,now).run();await env.DB.prepare('INSERT INTO activities(id,user_id,kind,summary,payload_json,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),user.id,kind,summary,JSON.stringify(payload||{}),now).run()}
async function overlays(env,origin,allowed){const edits=await env.DB.prepare('SELECT record_index,field,value,updated_at FROM record_overrides').all(),relationships=await env.DB.prepare('SELECT id,person_a_index,person_b_index,type,note,updated_at FROM relationships ORDER BY updated_at DESC').all(),merges=await env.DB.prepare('SELECT duplicate_index,primary_index,request_id,merged_by,merged_at FROM record_merges ORDER BY merged_at DESC').all();return reply({ok:true,overrides:edits.results||[],relationships:relationships.results||[],merges:merges.results||[]},200,origin,allowed)}
async function myActivity(request,env,origin,allowed){const user=await currentUser(request,env);if(!user)return reply({ok:false,error:'ابتدا وارد حساب شوید.'},401,origin,allowed);const rows=await env.DB.prepare('SELECT id,kind,summary,payload_json,created_at FROM activities WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(user.id).all();return reply({ok:true,user,activities:rows.results||[]},200,origin,allowed)}

async function listRecordVersions(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'تاریخچهٔ تغییرات فقط برای مدیر قابل مشاهده است.'},403,origin,allowed);const url=new URL(request.url),index=url.searchParams.get('record_index'),query=index===null?'SELECT v.*,u.username AS changed_by_name FROM record_versions v LEFT JOIN users u ON u.id=v.changed_by ORDER BY v.changed_at DESC LIMIT 200':'SELECT v.*,u.username AS changed_by_name FROM record_versions v LEFT JOIN users u ON u.id=v.changed_by WHERE v.record_index=? ORDER BY v.changed_at DESC LIMIT 200',rows=index===null?await env.DB.prepare(query).all():await env.DB.prepare(query).bind(Number(index)).all();return reply({ok:true,versions:rows.results||[]},200,origin,allowed)}
async function rollbackRecordVersion(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'بازگردانی نسخه فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),id=clean(input.id,80),version=await env.DB.prepare('SELECT * FROM record_versions WHERE id=?').bind(id).first();if(!version)throw new Error('نسخهٔ انتخاب‌شده پیدا نشد.');const current=await env.DB.prepare('SELECT value FROM record_overrides WHERE record_index=? AND field=?').bind(version.record_index,version.field).first(),restored=version.previous_value??'',now=new Date().toISOString(),newId=crypto.randomUUID();await env.DB.batch([env.DB.prepare("INSERT INTO record_versions(id,record_index,field,previous_value,new_value,action,changed_by,changed_at,reverted_from) VALUES(?,?,?,?,?,'rollback',?,?,?)").bind(newId,version.record_index,version.field,current?.value??null,restored,user.id,now,id),env.DB.prepare('INSERT INTO record_overrides(record_index,field,value,updated_by,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(record_index,field) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(version.record_index,version.field,restored,user.id,now)]);await logActivity(env,user,'record_rollback',`بازگردانی ${version.field} رکورد ${version.record_index}`,{version_id:id,restored});return reply({ok:true,record_index:version.record_index,field:version.field,value:restored,version_id:newId},200,origin,allowed)}

async function digest(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function sourceType(url){try{const host=new URL(url).hostname.toLowerCase();if(host.includes('openalex.org'))return'openalex';if(host.includes('github.com'))return'github';if(host.includes('instagram.com'))return'instagram';if(host.includes('t.me'))return'telegram';if(host.includes('eitaa.com'))return'eitaa';return'web'}catch{return'web'}}
async function inspectSource(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'user-agent':'SCIE-Source-Monitor/1.0','accept':'application/json,text/html;q=0.9,*/*;q=0.5'}}),type=response.headers.get('content-type')||'',text=(await response.text()).slice(0,250000),normalized=text.replace(/\s+/g,' ').trim();return {ok:response.ok,http_status:response.status,hash:normalized?await digest(`${response.url}\n${type}\n${normalized}`):'',error:response.ok?'':`HTTP ${response.status}`}}catch(error){return {ok:false,http_status:0,hash:'',error:clean(error.message,300)}}finally{clearTimeout(timer)}}
async function checkMonitor(env,row){const result=await inspectSource(row.source_url),now=new Date(),next=new Date(now.getTime()+(result.ok?7:2)*86400000).toISOString(),changed=Boolean(result.ok&&row.content_hash&&result.hash&&row.content_hash!==result.hash),status=result.ok?(changed?'changed':'healthy'):'unavailable';if(changed)await env.DB.prepare('INSERT INTO source_changes(id,record_index,previous_hash,current_hash,change_type,status,detected_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),row.record_index,row.content_hash,result.hash,'content_changed','pending',now.toISOString()).run();await env.DB.prepare('UPDATE source_monitors SET content_hash=CASE WHEN ? THEN ? ELSE content_hash END,last_status=?,http_status=?,last_checked_at=?,next_check_at=?,last_changed_at=CASE WHEN ? THEN ? ELSE last_changed_at END,error_message=? WHERE record_index=?').bind(result.ok?1:0,result.hash,status,result.http_status,now.toISOString(),next,changed?1:0,changed?now.toISOString():null,result.error,row.record_index).run();return {...row,...result,last_status:status,last_checked_at:now.toISOString(),next_check_at:next,changed}}
async function runDueMonitors(env,limit=40){const rows=await env.DB.prepare("SELECT * FROM source_monitors WHERE next_check_at IS NULL OR next_check_at<=? ORDER BY COALESCE(last_checked_at,'') ASC LIMIT ?").bind(new Date().toISOString(),Math.max(1,Math.min(100,limit))).all(),results=[];for(const row of rows.results||[])results.push(await checkMonitor(env,row));return results}
async function listSourceMonitors(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'پایش منابع فقط برای مدیر سامانه قابل مشاهده است.'},403,origin,allowed);const monitors=await env.DB.prepare('SELECT * FROM source_monitors ORDER BY CASE last_status WHEN \'changed\' THEN 0 WHEN \'unavailable\' THEN 1 WHEN \'queued\' THEN 2 ELSE 3 END,last_checked_at DESC LIMIT 5000').all(),changes=await env.DB.prepare("SELECT * FROM source_changes WHERE status='pending' ORDER BY detected_at DESC LIMIT 500").all();return reply({ok:true,monitors:monitors.results||[],changes:changes.results||[]},200,origin,allowed)}
async function registerSourceMonitors(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'ثبت پایش منابع فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),items=Array.isArray(input.sources)?input.sources.slice(0,5000):[];let accepted=0;for(const item of items){const index=Number(item.record_index),url=clean(item.source_url,900),name=clean(item.person_name,180);if(!Number.isInteger(index)||index<0||!/^https?:\/\//i.test(url))continue;await env.DB.prepare("INSERT INTO source_monitors(record_index,person_name,source_url,source_type,last_status,next_check_at) VALUES(?,?,?,?, 'queued',?) ON CONFLICT(record_index) DO UPDATE SET person_name=excluded.person_name,source_url=excluded.source_url,source_type=excluded.source_type,next_check_at=CASE WHEN source_monitors.source_url!=excluded.source_url THEN excluded.next_check_at ELSE source_monitors.next_check_at END").bind(index,name||`record-${index}`,url,sourceType(url),new Date().toISOString()).run();accepted++}await logActivity(env,user,'source_monitor_register',`ثبت ${accepted} منبع برای پایش`,{accepted});return reply({ok:true,accepted},200,origin,allowed)}
async function runSourceMonitors(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'اجرای پایش فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json().catch(()=>({})),results=await runDueMonitors(env,Number(input.limit)||40);await logActivity(env,user,'source_monitor_run',`بررسی ${results.length} منبع`,{changed:results.filter(item=>item.changed).length,unavailable:results.filter(item=>!item.ok).length});return reply({ok:true,checked:results.length,changed:results.filter(item=>item.changed).length,unavailable:results.filter(item=>!item.ok).length,results},200,origin,allowed)}
async function reviewSourceChange(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'بررسی تغییر منبع فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),id=clean(input.id,80),status=clean(input.action,20)==='accept'?'accepted':'dismissed',now=new Date().toISOString();await env.DB.prepare("UPDATE source_changes SET status=?,reviewed_by=?,reviewed_at=? WHERE id=? AND status='pending'").bind(status,user.id,now,id).run();await logActivity(env,user,'source_change_review',status==='accepted'?'تأیید تغییر منبع':'نادیده‌گرفتن تغییر منبع',{id,status});return reply({ok:true,status},200,origin,allowed)}
async function listSocialReviews(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'صف منابع اجتماعی فقط برای مدیر سامانه قابل مشاهده است.'},403,origin,allowed);const url=new URL(request.url),status=clean(url.searchParams.get('status')||'all',30),platform=clean(url.searchParams.get('platform')||'all',30),where=[],values=[];if(status!=='all'){where.push('status=?');values.push(status)}if(platform!=='all'){where.push('platform=?');values.push(platform)}const sql=`SELECT * FROM social_review_cases ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'needs_evidence' THEN 1 ELSE 2 END,last_seen_at DESC LIMIT 1000`,rows=await env.DB.prepare(sql).bind(...values).all(),stats=await env.DB.prepare("SELECT status,COUNT(*) AS count FROM social_review_cases GROUP BY status").all();return reply({ok:true,cases:rows.results||[],stats:stats.results||[]},200,origin,allowed)}
async function syncSocialReviews(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'همگام‌سازی صف فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),cases=Array.isArray(input.cases)?input.cases.slice(0,1000):[],now=new Date().toISOString(),statements=[];for(const item of cases){const sourceUrl=clean(item.url,900),platform=clean(item.platform||'other',40).toLowerCase(),reason=clean(item.reason||item.result,1000);if(!/^https?:\/\//i.test(sourceUrl))continue;statements.push(env.DB.prepare("INSERT INTO social_review_cases(id,source_url,platform,machine_reason,status,first_seen_at,last_seen_at) VALUES(?,?,?,?, 'pending',?,?) ON CONFLICT(source_url) DO UPDATE SET platform=excluded.platform,machine_reason=excluded.machine_reason,last_seen_at=excluded.last_seen_at").bind(crypto.randomUUID(),sourceUrl,platform,reason,now,now))}if(statements.length)await env.DB.batch(statements);await logActivity(env,user,'social_review_sync',`همگام‌سازی ${statements.length} مورد اجتماعی`,{count:statements.length});return reply({ok:true,synced:statements.length},200,origin,allowed)}
async function decideSocialReview(request,env,origin,allowed){const user=await currentUser(request,env);if(user?.role!=='admin')return reply({ok:false,error:'تصمیم نهایی فقط برای مدیر مجاز است.'},403,origin,allowed);const input=await request.json(),id=clean(input.id,80),decision=clean(input.decision,30),allowedDecisions=new Set(['needs_evidence','link_existing','create_candidate','irrelevant','relevant_nonperson']);if(!allowedDecisions.has(decision))throw new Error('تصمیم انتخاب‌شده معتبر نیست.');const item=await env.DB.prepare('SELECT * FROM social_review_cases WHERE id=?').bind(id).first();if(!item)throw new Error('پروندهٔ اجتماعی پیدا نشد.');const candidateName=clean(input.candidate_name,180),note=clean(input.note,1500),recordIndex=input.matched_record_index===''||input.matched_record_index===null||input.matched_record_index===undefined?null:Number(input.matched_record_index);if(decision==='link_existing'&&(!Number.isInteger(recordIndex)||recordIndex<0))throw new Error('برای اتصال، یک رکورد موجود را انتخاب کنید.');if(decision==='create_candidate'&&!candidateName)throw new Error('برای ایجاد نامزد، نام فرد را وارد کنید.');const status={needs_evidence:'needs_evidence',link_existing:'linked',create_candidate:'candidate_approved',irrelevant:'irrelevant',relevant_nonperson:'nonperson'}[decision],now=new Date().toISOString();let issueNumber=item.issue_number||null;if(decision==='create_candidate'&&env.GITHUB_TOKEN&&!issueNumber){const payload={id,kind:'source_review',source_url:item.source_url,platform:item.platform,verdict:'person_candidate',note:`نام تأییدشده توسط مدیر: ${candidateName}\n${note}`},issue=feedbackIssue(payload),response=await fetch(`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/issues`,{method:'POST',headers:{authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'SCIE-Social-Review','x-github-api-version':'2022-11-28'},body:JSON.stringify(issue)}),created=await response.json();if(response.ok)issueNumber=created.number}await env.DB.prepare('UPDATE social_review_cases SET status=?,decision=?,candidate_name=?,matched_record_index=?,reviewer_note=?,issue_number=?,reviewed_by=?,reviewed_at=? WHERE id=?').bind(status,decision,candidateName||null,Number.isInteger(recordIndex)?recordIndex:null,note||null,issueNumber,user.id,now,id).run();await logActivity(env,user,'social_review_decision',`تصمیم دربارهٔ منبع ${item.platform}`,{id,decision,status,source_url:item.source_url,candidate_name:candidateName,matched_record_index:recordIndex,issue_number:issueNumber});return reply({ok:true,status,decision,issue_number:issueNumber,reviewed_at:now},200,origin,allowed)}

export default {
  async fetch(request,env){
    const origin=request.headers.get('origin')||'',allowed=env.ALLOWED_ORIGIN;
    if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin,allowed)});
    if(origin!==allowed)return reply({ok:false,error:'مبدأ درخواست مجاز نیست.'},403,origin,allowed);
    try{
      const path=new URL(request.url).pathname;if(request.method==='GET'&&path==='/data/overlays')return await overlays(env,origin,allowed);if(request.method==='GET'&&path==='/me/activity')return await myActivity(request,env,origin,allowed);if(request.method==='GET'&&path==='/merges')return await listMerges(request,env,origin,allowed);if(request.method==='GET'&&path==='/admin/reverify')return await listReverification(request,env,origin,allowed);if(request.method==='GET'&&path==='/admin/source-monitors')return await listSourceMonitors(request,env,origin,allowed);if(request.method==='GET'&&path==='/admin/record-versions')return await listRecordVersions(request,env,origin,allowed);if(request.method==='GET'&&path==='/admin/social-reviews')return await listSocialReviews(request,env,origin,allowed);if(request.method!=='POST')return reply({ok:false,error:'متد درخواست مجاز نیست.'},405,origin,allowed);if(path==='/auth/register')return await authRoute(request,env,origin,allowed,'register');if(path==='/auth/login'||path==='/admin/login')return await authRoute(request,env,origin,allowed,'login');if(path==='/admin/record')return await d1UpdateRecord(request,env,origin,allowed);if(path==='/admin/record-versions/rollback')return await rollbackRecordVersion(request,env,origin,allowed);if(path==='/admin/import')return await importRecords(request,env,origin,allowed);if(path==='/admin/relationship')return await d1Relationship(request,env,origin,allowed);if(path==='/merges/propose')return await proposeMerge(request,env,origin,allowed);if(path==='/admin/merge')return await reviewMerge(request,env,origin,allowed);if(path==='/admin/reverify')return await createReverification(request,env,origin,allowed);if(path==='/admin/source-monitors/register')return await registerSourceMonitors(request,env,origin,allowed);if(path==='/admin/source-monitors/run')return await runSourceMonitors(request,env,origin,allowed);if(path==='/admin/source-monitors/review')return await reviewSourceChange(request,env,origin,allowed);if(path==='/admin/social-reviews/sync')return await syncSocialReviews(request,env,origin,allowed);if(path==='/admin/social-reviews/decide')return await decideSocialReview(request,env,origin,allowed);if(!env.GITHUB_TOKEN)return reply({ok:false,error:'سرویس هنوز پیکربندی نشده است.'},503,origin,allowed);
      const feedback=new URL(request.url).pathname==='/feedback',item=feedback?validateFeedback(await request.json()):validate(await request.json());
      const key=clean(request.headers.get('x-idempotency-key')||item.id,100);
      const cacheKey=new Request(`https://scie-idempotency.invalid/${encodeURIComponent(key)}`);
      const cached=await caches.default.match(cacheKey);if(cached)return new Response(cached.body,{status:cached.status,headers:cors(origin,allowed)});
      const issue=feedback?feedbackIssue(item):{title:`[SCIE LEAD] ${item.value}`,body:issueBody(item)};
      const response=await fetch(`https://api.github.com/repos/${env.GITHUB_REPOSITORY}/issues`,{method:'POST',headers:{authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'SCIE-Lead-API','x-github-api-version':'2022-11-28'},body:JSON.stringify(issue)});
      const result=await response.json();
      if(!response.ok)return reply({ok:false,error:'ارسال سرنخ به خط لوله ناموفق بود.',detail:result?.message||''},502,origin,allowed);
      const payload={ok:true,status:'submitted',issue_number:result.number,tracking_id:item.id};
      const user=await currentUser(request,env);if(user)await logActivity(env,user,feedback?'feedback':'lead',feedback?'ثبت مشارکت راستی‌آزمایی':`معرفی ${item.value}`,item);
      const success=reply(payload,202,origin,allowed);await caches.default.put(cacheKey,new Response(JSON.stringify(payload),{status:202,headers:{...JSON_HEADERS,'cache-control':'max-age=600'}}));return success;
    }catch(error){return reply({ok:false,error:error?.message||'درخواست معتبر نیست.'},400,origin,allowed)}
  },
  async scheduled(controller,env,ctx){ctx.waitUntil(runDueMonitors(env,60))}
};
